server:
  port: 80
#默认使用配置
spring:
  profiles:
    active: test
  freemarker:
    suffix: .html
    content-type: text/html
    cache: false
    charset: UTF-8
    request-context-attribute: request

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.luoxue.mybatis_demo.entity
  mapperLocations: classpath:mapper/*.xml



---
#开发配置
spring:
  profiles: prd
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_demo
    username: root
    password: luoxue
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

---
#测试配置
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_demo
    username: root
    password: abc
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource